In [3]:
import pandas as pd

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
df = pd.read_csv("/content/drive/MyDrive/University/8th Semester/BDAL/Project/student_lifestyle_100k.csv")

In [6]:
df.head()

,Student_ID,Age,Gender,Department,CGPA,Sleep_Duration,Study_Hours,Social_Media_Hours,Physical_Activity,Stress_Level,Depression
0,1001,22,Female,Science,3.50,7.3,3.3,3.4,114,5,False
1,1002,20,Male,Engineering,2.72,5.5,7.2,6.0,142,2,False
2,1003,20,Male,Medical,3.01,5.4,2.3,1.8,137,3,False
3,1004,21,Male,Engineering,3.63,8.1,2.0,4.6,130,3,False
4,1005,19,Male,Arts,3.14,6.8,2.6,4.3,4,6,False

In [7]:
df.shape

(100000, 11)

In [8]:
df.isnull().sum().sum()

np.int64(0)

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.dtypes

Student_ID              int64
Age                     int64
Gender                 object
Department             object
CGPA                  float64
Sleep_Duration        float64
Study_Hours           float64
Social_Media_Hours    float64
Physical_Activity       int64
Stress_Level            int64
Depression               bool
dtype: object

In [11]:
df["Gender"].unique()

array(['Female', 'Male'], dtype=object)

In [12]:
df["Department"].unique()

array(['Science', 'Engineering', 'Medical', 'Arts', 'Business'],
      dtype=object)

In [13]:
df["Depression"].unique()

array([False,  True])

In [14]:
df.describe()

,Student_ID,Age,CGPA,Sleep_Duration,Study_Hours,Social_Media_Hours,Physical_Activity,Stress_Level
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,51000.500000,21.009010,2.898316,6.996425,4.509517,3.503288,74.353180,4.131660
std,28867.657797,2.000382,0.532240,1.498682,1.976076,1.486852,43.366963,1.424151
min,1001.000000,18.000000,1.560000,3.000000,0.000000,0.000000,0.000000,2.000000
25%,26000.750000,19.000000,2.450000,6.000000,3.200000,2.500000,37.000000,3.000000
50%,51000.500000,21.000000,2.900000,7.000000,4.500000,3.500000,74.000000,4.000000
75%,76000.250000,23.000000,3.350000,8.000000,5.800000,4.500000,112.000000,5.000000
max,101000.000000,24.000000,4.000000,12.000000,12.800000,10.000000,149.000000,10.000000

In [15]:
df[(df["Age"] < 18) | (df["Age"] > 24)].shape[0]
df[(df["CGPA"] < 0) | (df["CGPA"] > 4)].shape[0]
df[(df["Sleep_Duration"] < 0)].shape[0]
df[(df["Study_Hours"] < 0)].shape[0]
df[(df["Social_Media_Hours"] < 0)].shape[0]
df[(df["Physical_Activity"] < 0)].shape[0]
df[(df["Stress_Level"] < 0) | (df["Stress_Level"] > 10)].shape[0]

0

In [16]:
df.head()

,Student_ID,Age,Gender,Department,CGPA,Sleep_Duration,Study_Hours,Social_Media_Hours,Physical_Activity,Stress_Level,Depression
0,1001,22,Female,Science,3.50,7.3,3.3,3.4,114,5,False
1,1002,20,Male,Engineering,2.72,5.5,7.2,6.0,142,2,False
2,1003,20,Male,Medical,3.01,5.4,2.3,1.8,137,3,False
3,1004,21,Male,Engineering,3.63,8.1,2.0,4.6,130,3,False
4,1005,19,Male,Arts,3.14,6.8,2.6,4.3,4,6,False

In [ ]:
# MapReduce
# Average CGPA by Department
# Average Stress Level by Gender
# Number of Students by Depression Status
# Pig
# Students with Stress Level > 7
# Average Study Hours by Department
# Average Sleep Duration by Depression Status
# Average CGPA by Depression Status
# Student Count by Gender